### ISSUE TITLE
Doesn't work on gentoo + python 3.4

### ISSUE THREAD

**Issue by temujin** [harlowja/gerrit_view#15]
Hi, guys.
I like things you do.
I've just cloned this repo, cd to it and made `pip install ./`

__________________________________
# qgerrit 
Traceback (most recent call last):
  File "/usr/bin/qgerrit", line 21, in <module>
    from itertools import ifilter, islice
ImportError: cannot import name 'ifilter'

__________________________________
# czuul
Traceback (most recent call last):
  File "/usr/bin/czuul", line 26, in <module>
    import thread
ImportError: No module named 'thread'

__________________________________
# cgerrit 
  File "/usr/bin/cgerrit", line 922
    raise exc_info[0], exc_info[1], exc_info[2]
                     ^
SyntaxError: invalid syntax

_____________________
# python --version
Python 3.4.3

# uname -srm
Linux 4.0.5-gentoo x86_64

# pip freeze
-lxc==0.1
bsddb3==6.0.1
CacheControl==0.11.5
certifi==2015.9.6.2
cffi==1.2.1
chardet==2.2.1
colorama==0.3.3
cryptography==1.0.2
Cython==0.22
decorator==4.0.2
distlib==0.2.1
ecdsa==0.11
gdbus-codegen==2.44.1
gentoolkit==0.3.0.9.post2
gerrit-view==0.4.6
gerritlib==0.4.0
html5lib==0.9999999
idna==2.0
ifilter==0.2
ipdb==0.8
ipython==3.2.1
isodate==0.5.1
java-config==2.2.0
jedi==0.8.1
Jinja2==2.7.3
lockfile==0.11.0
lxml==3.4.4
Magic-file-extensions==0.2
MarkupSafe==0.23
mock==1.3.0
ndg-httpsclient==0.4.0
netlink==1.0
numpy==1.9.2
packaging==15.3
paramiko==1.15.1
pbr==1.8.1
pexpect==3.3
ply==3.6
portage==2.2.20.1
prettytable==0.7.2
progress==1.2
pwquality==1.3.0
py==1.4.30
pyasn1==0.1.8
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.3.1
pyelftools==0.22
Pygments==2.0.2
PyOpenGL==3.0.2
pyOpenSSL==0.14
pyparsing==2.0.3
pyxattr==0.5.3
pyxdg==0.25
pyzmq==14.4.1
rdflib==4.1.2
requests==2.8.1
retrying==1.3.3
simplegeneric==0.8.1
simplejson==3.8.1
six==1.10.0
sloq==0.2

Thanks.

**Comment by harlowja** [comment]
If you want the programs probably need some updates for 3.4 feel free to send me a pull request and I'll merge it once ready.
